version: 2

builds:
  - main: ./cmd/macbroom
    binary: macbroom
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/lu-zhengda/macbroom/internal/cli.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - docs/man/*.1
      - completions/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

homebrew_casks:
  - repository:
      owner: lu-zhengda
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/lu-zhengda/macbroom"
    description: "A lightweight macOS cleanup tool"
    license: "MIT"
    binaries:
      - macbroom
    manpages:
      - docs/man/macbroom.1
    completions:
      bash: completions/macbroom.bash
      zsh: completions/macbroom.zsh
      fish: completions/macbroom.fish
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macbroom"]
          end
